name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Run release action
      run: |
        sudo apt-get update
        sudo apt-get install curl build-essential
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220323/llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        tar xf llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        rm llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
        PATH=$PWD/llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64/bin:$PATH ./build.sh
        rm -rf llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64
        zip -r winactivate-${{ steps.get_version.outputs.VERSION }}.zip README.md LICENSE bin/ winactivate.cmd winactivate.ps1 -x '*/.keep'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "winactivate-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
